# Generated by Django 5.1.2 on 2024-10-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ID',
            new_name='id',
        ),
    ]
